Main branch will be evaluated
kdprojects/microverse-hello-world pull request #3
Opened 2023-03-21 21:14 UTC by necrodevz

;

2023-03-21 23:18 UTC, tsohleDev requested changes
## Hi @necrodevz  

Good job so far!
There are some issues that you still need to work on.

![163947610-e4d849d5-e69c-49b9-90bd-a4191f4e2856](https://user-images.githubusercontent.com/97100091/191558701-8ed50201-3123-435c-89d8-29edcb66c64d.gif)

## Highlights!
- README template ✔️ 
- Descriptive commits ✔️ 
- Good branch name  ❌
- No linter errors ❌
- Descriptive pull request ❌
- All requirements met ❌

Hello ✋, you have done well creating your project 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

## Compliment
_Every comment with the [COMPLIMENT] prefix is not  a request, just a compliment at your skills_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@tsohleDev` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 23:18 UTC, tsohleDev commented on README.md
> +-->
- [x] I think it would be better if you remove the commented section of the template as this was only to guide you on how to use the template

as mentioned on line 25 of the template 😉 
> After you're finished please remove all comments and instructions!

2023-03-21 23:18 UTC, tsohleDev commented on src/index.css
> +}
- [x] At the moment your Linters checks are failing(red), I kindly suggest you look into this and try to fix it because Linters are very important for other developers to check that you meet the standards of their project and organization, and If you have any struggle about how to set up and check for Linters errors, you can read [here](https://github.com/microverseinc/linters-config) 😉

2023-03-21 23:18 UTC, tsohleDev commented on .gitignore
- [ ] I noticed that your Pull request does not have a descriptive title 😞 

![PR heading](https://user-images.githubusercontent.com/102636489/226761197-a21b7eac-d0fc-4aea-99a7-b2596008857a.png)

I kindly suggest you edit it and make it descriptive e.g
## Creating ...

with key features:
- 'key feature 1'
- 'key feature 2'

2023-03-21 23:18 UTC, tsohleDev commented on .github/workflows/linters.yml
- [ ] I noticed you named your branch name ``develop`` which does not describe the feature you have implemented in the branch. I think it would be better to rename the branch to a more descriptive name e.g ``created_sidebar`` or ``added_comments_section`` 😉

2023-03-23 15:05 UTC, closed without merging

2023-03-23 15:14 UTC, necrodevz commented
New PR https://github.com/kdprojects/microverse-hello-world/pull/5